exclude:
  - jekyll.*.sh
  - LICENSE

collections:
  systems:
    output: true

defaults:
  - scope:
      path: ""
      type: "systems"
    values:
      layout: "system"
  - scope:
      path: ""
    values:
      layout: "default"

# # GitHub Pages overrides
# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag