exclude:
  - jekyll.*.sh
  - LICENSE
  - old

defaults:
  - scope:
      path: systems/*
    values:
      layout: system
  - scope:
      path: games/*/*
    values:
      layout: game
  - scope:
      path: ""
    values:
      layout: default

theme: just-the-docs

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap
