exclude:
  - jekyll.*.sh
  - LICENSE
  - old

# collections:
#   systems:
#     output: true

defaults:
#   - scope:
#       path: ""
#       type: "systems"
#     values:
#       layout: "system"
  - values:
      layout: default

theme: just-the-docs

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap
